# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 01:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='birth_date',
            new_name='date',
        ),
        migrations.AddField(
            model_name='profile',
            name='lat',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='profile',
            name='lon',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='profile',
            name='number',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
