# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 20:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20170829_0120'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
