# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-31 03:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_profile_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='typer',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
